pulp/pulp_deb

extensions_admin/pulp_deb/extensions/admin/cudl.py
extensions_admin/pulp_deb/extensions/admin/pulp_cli.py
extensions_admin/test/unit/admin/test_cudl.py
extensions_admin/test/unit/admin/test_pulp_cli.py
plugins/pulp_deb/plugins/importers/web.py
plugins/test/unit/plugins/importers/test_web.py
run-tests.py

Implemented importing for Debian Packages.
Adds support for copying Packages from one Debian Repository to another.

add copy methods for pulp_deb

---

plugins/pulp_deb/plugins/distributors/configuration.py
plugins/test/unit/plugins/distributors/test_configuration.py

method lstrip of string does not alter the immutable string
rendering the the instruction a noop

get_repo_relative_path: move lstrip into return statement

---

docs/conf.py

Intersphinx is no longer used in the docs building process.
Removing it from config will allow to build docs locally or for
the plugin itself without any issues.
A key for the bugs link in the extlinks dictionary should be unique
across all the plugins. It's important to specify it in platform docs
config. But in plugin it's useful to have it as well: to have an ability
to build docs for the plugin only without platform ones.

Remove intersphinx config and fix link to bugs

---

README.md

@mibanescu 
Hello! I was trying to install the pulp debian plugin today on a fresh pulp 2.14 nightly build (installed via RPMs) on a Fedora 25 server. 
I could not find any install docs about what packages I needed to install, so I am making this PR. If this is not the right place to put these docs, or if you believe I have installed some extraneous packages, please let me know!

Add installation via package manager to README.md

---

plugins/pulp_deb/plugins/distributors/configuration.py
plugins/test/unit/plugins/distributors/test_configuration.py

Due to the bug (which i think is fixed here) it is impossible to change distributor options like `serve-http` without changing the `relative_path` alongside.
Together with the fix, tests were added.

Do not fail relative_path validation, when updating distributor

---

plugins/etc/httpd/conf.d/pulp_deb.conf
plugins/pulp_deb/plugins/distributors/distributor.py

Due to a misconfiguration (config now stolen from pulp_rpm) the options serve-http(s) were not really useful.

Fix http publishing

---

pulp-deb.spec

This commit fixes the issue:  
file /usr/lib/python2.7/site-packages/pulp_deb/extensions/__init__.pyc from install of pulp-deb-admin-extensions-1.5.2-1.el7.centos.noarch conflicts with file from package python-pulp-deb-common-1.5.2-1.el7.centos.noarch
file /usr/lib/python2.7/site-packages/pulp_deb/extensions/__init__.pyo from install of pulp-deb-admin-extensions-1.5.2-1.el7.centos.noarch conflicts with file from package python-pulp-deb-common-1.5.2-1.el7.centos.noarch

Fixed duplicate file conflict in RPM spec

---

README.md

Somehow, the signer gets called twice (http and https?). So deleting the
old signature first assures, that gpg will not fail.

Update sign example

---

plugins/pulp_deb/plugins/distributors/configuration.py
plugins/test/unit/plugins/distributors/test_configuration.py
plugins/test/unit/plugins/distributors/test_distributor.py

Since the command configured with gpg_cmd executes remotely as user apache,
a user should not be allowed to change it via a distributor config or
an override at publish time.
Fixes #3498
https://pulp.plan.io/issues/3498
Change-Id: I88cdb4f51c237b1157e7424863df7049269939ca

gpg_cmd is not allowed as plugin or override configuration

---

pulp-dev.py

Since the spec file is no longer available, we cannot parse it any more when installing the pip dependencies.
On another thought, should they be available as rpm's already?

Fix installing the pip dependencies

---

plugins/pulp_deb/plugins/importers/sync.py

Add backwards-compatibility for:
* older pulp-versions (`get_boolean()` without default-value)
* older gnupg-versions (`homedir` vs. `gnupghome`, order of parameters in `verify()`)
Moved determining keyserver out of loop.

Verify fingerprints compatibility

---

plugins/pulp_deb/plugins/distributors/distributor.py
plugins/test/unit/plugins/distributors/test_distributor.py

Fix the 'Label' and the 'Description' in the repo metadata (Release file).
This enables Apt Pinning because pinning uses this metadata to distinguish between repos.
Fixes #3917
https://pulp.plan.io/issues/3917

Fix repo metadata information

---

plugins/setup.py

bc9c24693cb9c6db8cbcd565d11ed6ecb6ad178f added gnupg as a dependency but it wasn't declared as such.

Add missing gnupg dependency + correct indenting in setup.py

---

plugins/setup.py

while you `import gnupg`, the package is called `python-gnupg` on PyPI
otherwise Pulp fails to load it:
Loading unit model: deb_release = pulp_deb.plugins.db.models:DebRelease
gnupg
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/pulp/server/db/manage.py", line 236, in main
return _auto_manage_db(options)
File "/usr/lib/python2.7/site-packages/pulp/server/db/manage.py", line 267, in _auto_manage_db
old_content_types = load_content_types(dry_run=options.dry_run)
File "/usr/lib/python2.7/site-packages/pulp/plugins/loader/api.py", line 438, in load_content_types
mongoengine_definitions = _generate_plugin_definitions()
File "/usr/lib/python2.7/site-packages/pulp/plugins/loader/api.py", line 519, in _generate_plugin_definitions
plugin_manager = PluginManager()
File …

fix the gnupg package name in setup

---

plugins/test/unit/plugins/distributors/test_configuration.py

Without this change Travis CI builds will always fial.

Satisfy flake8

---

README.md

Support for keys that state a preference for SHA-1 encryption has been turned off in APT as of Debian 9. (Specifically, it was turned off in APT version 1.4~beta1, and Debian 9 has version 1.4.7.)

Force digest-algo to SHA256

---

plugins/test/unit/plugins/importers/test_sync.py

The `test_VerifySignature` test will not run on my `devel_pulp2_dev` Vagrant box without this line.
Instead it throws a `raise Exception("No GPG-keys in keyring, did the import fail?")`.
Since Travis appears to be doing fine without this fix, it would be good to know if others are having the same problem, or what the difference between Travis and my local Vagrant box is...
Edit: I added a pulp.plan.io issue to go with this PR:
https://pulp.plan.io/issues/4332

Fix test_VerifySignature on devel

---

plugins/pulp_deb/plugins/db/models.py
plugins/pulp_deb/plugins/distributors/configuration.py
plugins/pulp_deb/plugins/distributors/distributor.py
plugins/pulp_deb/plugins/distributors/metadata_files.py
plugins/pulp_deb/plugins/importers/sync.py
plugins/pulp_deb/plugins/migrations/0003_add_multiple_hashes.py
plugins/test/testbase.py
plugins/test/unit/plugins/db/test_models.py
plugins/test/unit/plugins/distributors/test_distributor.py
plugins/test/unit/plugins/importers/test_importer.py
plugins/test/unit/plugins/importers/test_sync.py

This pull request aims to improve the performance of the MetadataStep when dealing with large Debian repositories (e.g. stretch/main). This is achieved by completely removing the debpkgr dependency from this step. The needed functionality is instead implemented directly in pulp_deb.
This pull request is intended as a pure code refactor that does not add or remove any features. (Though I have several ideas for follow on improvements including bug fixes and new features that would be easy to implement on top of these changes). The only "feature changes" I am aware of is that the relative order of fields in both 'Packages' and 'Release' files will have changed (I used the same order I found in upstream Debian Stretch mirrors), and that I no longer write redundant information into 'Release' …

MetadataStep performance

---

plugins/pulp_deb/plugins/importers/sync.py

The components in the repo metadata object ('Release' file) may be
prefixed. This prefix must be stripped from certain comparisons.
See also: https://wiki.debian.org/DebianRepository/Format#Components
~~Also sets the 'suite' correctly~~. (EDIT: This has already been fixed in master).
Fixes #4008
https://pulp.plan.io/issues/4008
~~WARNING: These changes are dependent on changes in python-debpkgr to work (as well as to fully resolve the issue).
Do not merge/release before the following pull request has made it into python-debpkgr:
https://github.com/sassoftware/python-debpkgr/pull/13~~
EDIT: With the merge of https://github.com/pulp/pulp_deb/pull/57 into master, the dependency to python-debpkgr https://github.com/sassoftware/python-debpkgr/pull/13 no longer exists!

Account for components with an extra path prefix

---

plugins/pulp_deb/plugins/distributors/distributor.py

When publishing an old copy of a Repository, it can happen, that the
component references packages not yet in that version.

Safely select packages to symlink in components

---

plugins/pulp_deb/plugins/importers/sync.py
plugins/test/unit/plugins/importers/test_sync.py

If the long-description of a package contains an erroneous newline, the
rest of the paragraph is considered to describe a new package, but it is
incomplete. We try to ignore those and hope for the best.
Usually there is only the 'Homepage' field, so no functionality should be
affected.
Thanks to @sbernhard for analysing the problem.

Ignore invalid paragraphs in package indices

---

common/pulp_deb/common/ids.py
extensions_admin/pulp_deb/extensions/admin/units_display.py
plugins/pulp_deb/plugins/db/models.py
plugins/pulp_deb/plugins/distributors/distributor.py
plugins/pulp_deb/plugins/importers/sync.py
plugins/pulp_deb/plugins/migrations/0004_add_distribution.py
plugins/test/unit/plugins/distributors/test_distributor.py
plugins/test/unit/plugins/importers/test_sync.py
plugins/types/deb.json

**DEPENDS ON:** https://github.com/pulp/pulp/pull/3919 (https://pulp.plan.io/issues/4871)
**Fixes**:
- https://pulp.plan.io/issues/4138
- https://pulp.plan.io/issues/4705
- https://pulp.plan.io/issues/4707
**Relates to**:
- https://pulp.plan.io/issues/3464 (fixes it in pulp, but also needs to be fixed in `python-debpkgr`)
**Background**
Debian repositories are generally structured into multiple "releases" or "distributions", each associated with a single "Release" file somewhere within the `/dists/` folder of the repository.
Most commonly such release files are placed within the folder in one of two ways:
/dists/<codename>/Release
/dists/<suite>/Release
Pulp currently publishes all `Release` files under the `<codename>` path.
However, the official specification allows for the following …

Add a "distribution" field

---

plugins/pulp_deb/plugins/migrations/0004_add_distribution.py

I am adding this PR so I can ask if this could still be included (release schedule wise), and whether we would want a Katello specific work around in pulp.
While non essential, this change will greatly improve the user experience of Katello pulp_deb users and is highly unlikely to affect anyone else.
ATIX will almost certainly add this change (or something feature equivalent) to the pulp instance we package with our orcharhinos.
In addition to the Katello work around, I have also improved the logging. This should be particularly valuable for analysis if the migration produces unexpected results.
My apologies for springing this on everyone after the dev freeze, but I wanted to at least put it up for discussion.

Katello support for migration 0004

---

plugins/pulp_deb/plugins/distributors/distributor.py
plugins/test/unit/plugins/distributors/test_distributor.py

fixes #4345
https://pulp.plan.io/issues/4345
The current behavior of pulp_deb is not to publish anything if repositories are empty (contain no packages).
This prevents pulp to pulp syncs and may be a problem for clients configured to use a repository with an empty publish directory.
By simply removing a guard the publish mechanism works as expected producing a valid empty repository complete with Release and (empty) Packages file.
The only limitation is that because of https://pulp.plan.io/issues/4094 the only architecture that will be published is the `all` architecture. However, this can be fixed as a separate issue.

Make pulp_deb publish empty repositories.

---

CHANGES/5376.doc
CHANGES/5380.doc
docs/installation.rst
docs/workflows/publish.rst
docs/workflows/upload.rst

* installation docs should reference services
* update "publisher" to "publication"
* remove "publish a repo" as that's not a thing anymore
* update content creation to reflect the current API
* fix various formatting
fixes: #5380
ref: #5376
Signed-off-by: Phil Dibowitz <phil@ipom.com>

Various fixes to the pulp_deb docs

---

pulp_deb/app/serializers/content_serializers.py
pulp_deb/tests/functional/utils.py

The fields _artifact and _relative_path on the SingleArtifactSerializer
have been renamed to artifact and relative_path.
[noissue]

Rename fields on Serializers

---

CHANGES/5304.misc
pulp_deb/app/tasks/publishing.py

Required PR: pulp/pulpcore#303
re: #5304
https://pulp.plan.io/issues/5304

Switch to using PublishedMetada.create_from_file()

---

pulp_deb/tests/functional/api/test_download_policies.py
pulp_deb/tests/functional/constants.py

This has so far prevented the use of the fixtures container for Travis tests.
Depends on https://github.com/pulp/pulp-fixtures/pull/145

Use the PULP_FIXTRUES_BASE_URL from config

---

common/pulp_deb/common/constants.py
plugins/pulp_deb/plugins/db/models.py
plugins/pulp_deb/plugins/importers/sync.py
plugins/test/unit/plugins/importers/test_sync.py

If force full mode is active, existing packages are validated and if needed
rescheduled for download.
closes #5170
https://pulp.plan.io/issues/5170

Add validation of existing packages to sync

---

plugins/pulp_deb/plugins/importers/sync.py
plugins/test/unit/plugins/importers/test_sync.py

Since lookup in dicts is logarithmic, this should improve performance
significantly if a large number of old content units are to be checked
for removal (i.e. when switching a huge repository to another
architecture).

Use dictionaries for units_to_check

---

CHANGES/6052.misc
pulp_deb/app/tasks/synchronizing.py
pulp_deb/tests/functional/api/test_sync.py
pulp_deb/tests/functional/constants.py

Depends on https://github.com/pulp/pulp-fixtures/pull/147
ref #6052
https://pulp.plan.io/issues/6052
Has been fully tested with a local build of the pulp-fixtures container.

Add sync tests for invalid Debian fixtures

---

CHANGES/6396.doc
docs/bindings.rst

https://pulp.plan.io/issues/6221
ref #6221

Bindings installation on dev environment

---

CHANGES.rst
CHANGES/6050.bugfix
CHANGES/6052.misc
CHANGES/6171.feature
CHANGES/6383.bugfix
CHANGES/6393.misc
CHANGES/6396.doc
pulp_deb/__init__.py
setup.py

I have prepared this PR for creating a `pulp_deb` `2.3.0b1` beta release, compatible to pulpcore `2.3`.
I believe I do not have the required permissions to actually create this beta release, which is why this is a "Draft pull request".
If I have understood everything correctly, I need someone to do the following in order to create the Release:
1. Review these changes
1. Create a branch named `2.3` at commit 662daab and push it to `pulp/pulp_deb`
1. Create a tag named `2.3.0b1` at the same commit and push it to `pulp/pulp_deb`
1. Check if the pipeline successfully released to https://pypi.org/project/pulp-deb/
1. Merge this PR

Prepare 2.3.0b1 (beta) release

---

CHANGES/6787.bugfix
pulp_deb/app/tasks/publishing.py

fixes #6787
https://pulp.plan.io/issues/6787
Ensures packages with architecture 'all' are added to all available
package indecies, rather than a non existent 'all' package index.
Note: I believe we can create test coverage for this change, by simply adding some `architecture=all` type packages to the existing fixture repos. I will open a separate PR against https://github.com/pulp/pulp-fixtures

Fix structured publishing

---

CHANGES/6869.feature
pulp_deb/app/tasks/publishing.py

fixes #6869
https://pulp.plan.io/issues/6869
See also:
https://wiki.debian.org/DebianRepository/Format#Date.2C_Valid-Until

Add Date field to Release files during publish

---

CHANGES/6876.bugfix
pulp_deb/app/tasks/publishing.py

fixes #6876
https://pulp.plan.io/issues/6876
I also fixed several instances of using the codename in paths. Codenames
should never be used in paths. Always use the "distribution" in paths.
ref #6051
https://pulp.plan.io/issues/6051

Use the correct relative paths in Release files

---

CHANGES.rst
CHANGES/6787.bugfix
CHANGES/6869.feature
CHANGES/6876.bugfix
pulp_deb/__init__.py
setup.py

This is mainly needed so people can install the plugin along with pulpcore `3.4`.
This nevertheless remains a beta release!

Prepare release 2.4.0b1 (beta)

---

CHANGES/6982.bugfix
pulp_deb/app/serializers/content_serializers.py

fixes APT client installing same packages again and again due to missing installed_size.
fixes #6982
https://pulp.plan.io/issues/6982

Fix APT client installing patches

---

CHANGES.rst
CHANGES/6897.misc
CHANGES/6907.feature
CHANGES/6908.bugfix
CHANGES/6982.bugfix
pulp_deb/__init__.py
setup.py

[noissue]
* Removed .dev from the version
* Adjusted the pulpcore requirement
* Ran towncrier in the project root (no manual changes)
* Finally bumped to the next development version (`2.6.0b1.dev`) in a second commit.

 Prepare the 2.5.0b1 release

---

plugins/pulp_deb/plugins/importers/sync.py
plugins/test/unit/plugins/db/test_models.py
pulp-dev.py

It looks like a newer version of python2-gnupg now expects the gnupg
home folder to exist before any keys are imported (whereas the older
version presumably just created it if it was not there already).

Fix gnupg metadata verification

---

CHANGES/6882.misc
README.md
requirements.txt
setup.py

fixes #6882
https://pulp.plan.io/issues/6882
The motivation was to provide a "project description" on pypi.org. This
necessitated another rework of the README.md file to make it usable for
arbitrary locations. There was some minor cleanup of setup.py as
informed by pulpcore and pulp_rpm.

Add a long_description to the python package

---

CHANGES/7355.doc
docs/_static/api.json
pulp_deb/app/viewsets/content.py
pulp_deb/app/viewsets/publication.py
pulp_deb/app/viewsets/remote.py
pulp_deb/app/viewsets/repository.py

fixes #7355
https://pulp.plan.io/issues/7355
Motivated by https://github.com/pulp/pulp_deb/pull/198
The existing REST API docs (for reference): https://pulp-deb.readthedocs.io/en/latest/restapi.html

Add meaningful REST API endpoint descriptions

---

CHANGES/6429.doc
CHANGES/6429.feature
docs/feature_overview.rst
pulp_deb/app/models/content.py
pulp_deb/app/models/repository.py

Add uniqueness constraint for debian repository versions such that there are no duplicate packages in repository.
fixes #6429
https://pulp.plan.io/issues/6429

Add per repository package uniqueness constraints

---

.bumpversion.cfg
CHANGES.rst
CHANGES/6051.misc
CHANGES/6429.doc
CHANGES/6429.feature
CHANGES/6506.doc
CHANGES/6882.misc
CHANGES/6991.bugfix
CHANGES/7148.doc
CHANGES/7153.bugfix
CHANGES/7190.bugfix
CHANGES/7211.doc
CHANGES/7236.bugfix
CHANGES/7257.bugfix
CHANGES/7295.bugfix
CHANGES/7318.doc
CHANGES/7344.misc
CHANGES/7355.doc
pulp_deb/__init__.py
requirements.txt
setup.py

Generated using `python .travis/release.py minor --lower 3.6 --upper 3.7` plus some manual edits to the change log.

Release 2.6.0b1

---

.bumpversion.cfg
.travis.yml
.travis/release.py
CHANGES/6999.misc
pulp_deb/__init__.py
setup.py
template_config.yml

fixes #6999
https://pulp.plan.io/issues/6999
* Drops all beta tags
* Enables the update_redmine setting for Travis.

Prepare master for GA status

---

.travis/release.py
pyproject.toml

This fixes the milestone_id issue,
but now I'm facing some weird  `towncrier` issue:
```
pulp_deb on  milestone_id via 🐍 v3.8.0 (venv) took 4s 
❯ towncrier --version 2.7.0  
Loading template...
Finding news fragments...
Rendering news fragments...
Tried to import pulp-deb, but ran into this error: No module named 'pulp-deb'
Traceback (most recent call last):
File "/home/faguiar/.pyenv/versions/venv/bin/towncrier", line 8, in <module>
sys.exit(_main())
File "/home/faguiar/.pyenv/versions/3.8.0/envs/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/home/faguiar/.pyenv/versions/3.8.0/envs/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File …
```

Fix milestone_id issue

---

.travis.yml
.travis/install.sh
.travis/post_before_script.sh
template_config.yml

[noissue]
I am still unsure what exactly the benefit is/if this is needed for `pulp_deb`, but I thought it does not hurt to test it out.

Enable test_s3 in the template config

---

pulp_deb/tests/functional/api/test_sync.py

Changes in file pulp_deb/tests/functional/api/test_sync.py according to
https://www.redhat.com/archives/pulp-dev/2020-September/msg00013.html

Remove ``test_file_descriptors``

---

docs/external_references.rst
docs/plugin_maintenance.rst

[noissue]
This reflects the lessons learned from the 2.7.0 release.
See: https://github.com/pulp/pulp_deb/pull/219

Update the release documentation

---

pulp_deb/tests/functional/setup_signing_service.py

This sets a default for DJANGO_SETTINGS_MODULE which means the user doesn't have to specify it anymore. Since it's a default, the user can still override it. This follows recent commits to pulpcore itself.

Set default for DJANGO_SETTINGS_MODULE

---

.github/workflows/scripts/before_install.sh
CONTRIBUTING.rst
README.md
docs/conf.py
docs/external_references.rst
docs/plugin_maintenance.rst

[noissue]
With this change, I will need to push a new branch `main`, change the repositories default branch to it, add the branch protection rule, and finally delete the `master` branch.

Rename the master branch to main

---

docs/external_references.rst
docs/index.rst

[noissue]
I frequently find myself wanting to navigate from the docs to one or more of these places.
Some of these URLs are already available embedded within text, but IMHO a list is more user friendly to returning users.

Add a list of the most important URLs to the docs

---

CHANGES/8388.bugfix
CHANGES/8388.doc
docs/external_references.rst
docs/workflows.rst
docs/workflows/checksums.rst
pulp_deb/app/serializers/content_serializers.py
pulp_deb/app/settings.py
pulp_deb/app/tasks/publishing.py
pulp_deb/app/tasks/synchronizing.py
pulp_deb/constants.py

fixes #8388
https://pulp.plan.io/issues/8388
TODO:

Handle ALLOWED_CONTENT_CHECKSUMS parameter

---

CHANGES/8556.bugfix
pulp_deb/app/tasks/synchronizing.py

Backports #8410
Fixes #8556
https://pulp.plan.io/issues/8556
https://pulp.plan.io/issues/8410
https://pulp.plan.io/issues/8096
(cherry picked from commit 580f0e725a3a47e181eb582fbe8ba33a35c5b1e6)

Fix translation file synchronization

---

CHANGES/8558.bugfix
pulp_deb/app/tasks/synchronizing.py

Fixes #8558
Backports #8410
https://pulp.plan.io/issues/8558
https://pulp.plan.io/issues/8410
https://pulp.plan.io/issues/8096
(cherry picked from commit 580f0e725a3a47e181eb582fbe8ba33a35c5b1e6)

Backport 2.10: Fix translation file synchronization

---

pulp_deb/app/viewsets/publication.py
pulp_deb/app/viewsets/repository.py

[noissue]
ref #8682
https://pulp.plan.io/issues/8682

Use dispatch instead of deprecated enqueue_with_reservation

---

CHANGES/8671.bugfix
pulp_deb/app/tasks/synchronizing.py

Closes #8671
https://pulp.plan.io/issues/8671
This feature has never fully worked, the implementation is incomplete
and causes various sync failures. Re-adding this feature should be done
under the following story: https://pulp.plan.io/issues/8734

Completely disable synchronization of translation files

---

CHANGES/8735.bugfix
pulp_deb/app/tasks/synchronizing.py

Closes #8735
Backports #8671
https://pulp.plan.io/issues/8671
This feature has never fully worked, the implementation is incomplete
and causes various sync failures. Re-adding this feature should be done
under the following story: https://pulp.plan.io/issues/8734
(cherry picked from commit 98f25d846f41fc817501451daef39118d18d06b2)

Backport 2.12: Completely disable synchronization of translation files

---

CHANGES/8736.bugfix
pulp_deb/app/tasks/synchronizing.py

Closes #8736
Backports #8671
https://pulp.plan.io/issues/8671
This feature has never fully worked, the implementation is incomplete
and causes various sync failures. Re-adding this feature should be done
under the following story: https://pulp.plan.io/issues/8734
(cherry picked from commit 98f25d846f41fc817501451daef39118d18d06b2)

Backport 2.11: Completely disable synchronization of translation files

---

CHANGES/8738.bugfix
pulp_deb/app/tasks/synchronizing.py

Closes #8738
Backports #8671
https://pulp.plan.io/issues/8671
This feature has never fully worked, the implementation is incomplete
and causes various sync failures. Re-adding this feature should be done
under the following story: https://pulp.plan.io/issues/8734
(cherry picked from commit 98f25d846f41fc817501451daef39118d18d06b2)

Backport 2.9: Completely disable synchronization of translation files

---

CHANGES/8828.bugfix
pulp_deb/app/tasks/synchronizing.py

Closes #8828
https://pulp.plan.io/issues/8828
When creating an intersection between the release file components and
the components from the remote, we need to consider the special case,
where the release file components have a path prefix, but those from the 
remote do not!

Consider that release file components may not be plain components

---

pulp_deb/app/viewsets/publication.py
pulp_deb/app/viewsets/repository.py

[noissue]
The need to do this was undeprecated as it is now performed in pulpcore.

Do not explicitly cast primary keys to str

---

pulp_deb/tests/unit/test_sync_helpers.py

[noissue]
Having recently reworked these filter functions several times in a row to accommodate all kinds of edge cases, I feel like they would really benefit from some simple unit tests!

Add unit tests to test component and architecture filtering

---

pulp_deb/app/tasks/synchronizing.py

[noissue]
A user posted the error on the pulp matrix channel, so I decided to add the hint I gave right in the error message.

Add continuation hint to NoPackageIndexFile error message

---

CHANGES.rst

[noissue]
Cherry-pick this to the `2.14` branch BEFORE 2.14.1 is released!

Add warning to changelog about 2.14.0 release

---

CHANGES/9162.misc
pulp_deb/app/serializers/content_serializers.py
requirements.txt

Closes #9162
https://pulp.plan.io/issues/9162

Add touch statements to prevent false positives during orphan cleanup

---

CHANGES/9175.misc
pulp_deb/app/serializers/content_serializers.py
requirements.txt

backports #9162
https://pulp.plan.io/issues/9162
fixes #9175
(cherry picked from commit d52881a1e006f9efb06acf13ecaca857f6af7d13)

Backport #9162 to 2.14: Add touch statements to prevent false positives during orphan cleanup

---

docs/installation.rst

Installation guide seems obsolete on db migration
instructions.
Signed-off-by: ushen <yshxxsjt715@gmail.com>

Fix  db migration doc

---

CHANGES/9167.bugfix
functest_requirements.txt
pulp_deb/app/serializers/content_serializers.py
pulp_deb/app/tasks/synchronizing.py
pulp_deb/tests/functional/api/test_publish_complex_dists.py
pulp_deb/tests/unit/test_models.py

also added some more detailed tests for published package-indizes
backports #8506
https://pulp.plan.io/issues/8506
fixes #9167
(cherry picked from commit f4172f489c59022fa93256b5781ec34eae8bef99)

Backport to 2.13: Add missing "Size" field in publications

---

.github/workflows/release.yml

[noissue]
With the way I have been handling changelog for pulp_deb, this job is
doomed to fail for older release branches (unresolvable merge conflict)!
I will do this manually instead.

Disable changelog to main branch CI jobs for 2.13

---

CHANGES/7673.bugfix
pulp_deb/app/models/content.py
pulp_deb/app/serializers/content_serializers.py
pulp_deb/app/tasks/publishing.py
pulp_deb/app/tasks/synchronizing.py
pulp_deb/tests/functional/api/test_publish_flat_repo_format.py

Closes #7673
https://pulp.plan.io/issues/7673
With this change flat repo syncs will work even if the upstream Release
file contains no "Components" or "Architectures" fields. In addition we
are ensuring flat repo syncs do not attempt to sync installer files or
packages.

Make flat repo syncs more robust

---

requirements.txt

Pin python-debian to <0.1.42 to prevent breakage against python <3.7

---

CHANGES/8756.bugfix
pulp_deb/app/models/repository.py
requirements.txt

closes #8756
https://pulp.plan.io/issues/8756
In particular, this allows us to synchronize repos using mirror=false
option.
Requires https://github.com/pulp/pulpcore/pull/1726

Fix mirrored metadata handling when creating new repo versions

---

CHANGES/9563.bugfix
pulp_deb/app/serializers/publication_serializers.py

Signed-off-by: Joshua Schmid <jaiks@posteo.de>
fixes: https://pulp.plan.io/issues/9563

Reference signing services via pulp_href (like everything else)

---

CHANGES/432.bugfix
CHANGES/433.bugfix
pulp_deb/app/serializers/content_serializers.py
pulp_deb/app/serializers/publication_serializers.py

2.16 cherrypicks

---

CHANGES/422.bugfix
pulp_deb/app/tasks/synchronizing.py

Handle upstream package indices containing packages with a wrong architecture

---

pulp_deb/app/tasks/synchronizing.py

[noissue]
This fixes the fix introduced by commit 041638348533e8bfe6be08a8d4bcf6d8dab6eb13
Fortunately this has been caught before it was released!

Fix wrong architecture in index handling

---

CHANGES/396.feature
MANIFEST.in
docs/feature_overview.rst
pulp_deb/app/schema/__init__.py
pulp_deb/app/schema/copy_config.json
pulp_deb/app/serializers/__init__.py
pulp_deb/app/serializers/repository_serializers.py
pulp_deb/app/tasks/__init__.py
pulp_deb/app/tasks/copy.py
pulp_deb/app/urls.py
pulp_deb/app/viewsets/__init__.py
pulp_deb/app/viewsets/repository.py

Adds Copy mechanism to be used by Katello to copy content in CV filters

Add advanced copy mechanism in Pulp3 DEB without dependency_solving

---

pulp_deb/app/tasks/synchronizing.py

[noissue]
~~I am fairly certain, this condition never happens.~~ The only way for the underlying functions not to return anything should involve them throwing unhandled errors.
Further evidence: We routinely end up within the conditional in line 688, which checks for a very similar condition.
I am happy for the tests to convince me I am wrong of course! :stuck_out_tongue_winking_eye:

Improve log message

---

CHANGES/456.misc
flake8.cfg
pulp_deb/app/tasks/synchronizing.py
pulp_deb/tests/functional/api/test_sync.py

Closes #456
When a repo uses "No-Support-for-Architecture-all: Packages" style
format, we should not warn about all architecture packages in
architecture specific package indices! They are expected to be there!
We still skip those packages since there is no need to download them
twice!
When a mirror mirrors metadata indicating
"No-Support-for-Architecture-all: Packages" format, while failing to
mirror the binary-all package indices we introduce special handling to
ensure we nevertheless sync "Architecture: all" packages.

Rework No-Support-for-Architecture-all repo format sync handling

---

requirements.txt

[noissue]
It looks like the release CI now requires upper bounds on all dependencies: https://github.com/pulp/pulp_deb/runs/6102557469?check_suite_focus=true

Add upper bounds to requirements for release CI

---

pulp_deb/app/tasks/synchronizing.py

DeclarativeArtifacts parameters need to explicitly set.
See: https://github.com/pulp/pulp_python/pull/536/files

Fix local tests broken by DeclarativeArtifacts

---

requirements.txt

This is in anticipation of the pulpcore 3.20 breaking release, for which
there are already adjustments in the pulp_deb master.

Raise the pulpcore floor to 3.20

---

CHANGES/601.bugfix
pulp_deb/app/tasks/publishing.py

closes #601
This occurs when an upstream repo contains a distribution named
"default" and we then try to publish using both "simple=True" and
"structured=True".

Handle duplicate "default" distribution publications

---

CHANGES/564.feature
pulp_deb/app/serializers/__init__.py
pulp_deb/app/serializers/repository_serializers.py
pulp_deb/app/tasks/synchronizing.py
pulp_deb/app/viewsets/repository.py
pulp_deb/tests/functional/api/test_download_content.py
pulp_deb/tests/functional/api/test_download_policies.py
pulp_deb/tests/functional/api/test_publish.py
pulp_deb/tests/functional/api/test_publish_complex_dists.py
pulp_deb/tests/functional/api/test_publish_empty_repository.py
pulp_deb/tests/functional/api/test_publish_flat_repo_format.py
pulp_deb/tests/functional/api/test_pulpexport.py
pulp_deb/tests/functional/api/test_pulpimport.py
pulp_deb/tests/functional/api/test_sync.py
pulp_deb/tests/functional/api/test_sync_missing_architecture.py
pulp_deb/tests/functional/api/test_sync_optimize.py
pulp_deb/tests/functional/constants.py
requirements.txt

Required PR: https://github.com/pulp/pulpcore/pull/2999
closes #564
Co-Authored-By: Quirin Pamp <pamp@atix.de>
This will change the default behaviour of the sync to use optimize
unless it is explicitly set to False.

Add optimize mode for sync tasks

---

CHANGES/632.bugfix
pulp_deb/app/models/repository.py

closes #632
Using validate_duplicate_content prevents successfull synchronization
when multiple package indices contain references to the same package.
However, this is an entirely legitimate situation for separate
distributions/releases within a single APT repo. Further more, the so
created duplicate package content, does not cause any adverse effects,
since it is actually identical and only one of each duplicate will be
saved.
Note that this issue was masked prior to the introduction of the
optimize sync feature, since we were inadvertently using the Repository
class from pulpcore instead of the AptRepository class from pulp_deb.

Do not validate_duplicate_content for APT repositories

---

requirements.txt

[noissue]
Note that I have no intention of making any django or drf dependencies
explicit. I want those to be handled by pulpcore. If pulpcore decides to
throw something out, I *want* things to break, so I am forced to fix
them for the next release.
Other candidates for handling via pulpcore: asgiref, asyncio, aiohttp

Make more dependencies explicit

---

CHANGES/660.doc
docs/feature_overview.rst

The previous documentation was brief to the point of being opaque. This should at least help people get started until more thorough workflow documentation is available.

Improve documentation on metadata signing

---

pulp_deb/app/viewsets/repository.py

The `mirror` field defaults to False in the RepositorySyncURLSerializer:
https://github.com/pulp/pulpcore/blob/ab7f4b7c7e1939ae605a8d7cf996c6498c83ddd7/pulpcore/app/serializers/repository.py#L336
So it should always be set and it should be False by default. This line however gives the impression that mirror is True by default so update it so it no longer has a default. This shouldn't impact users.
[noissue]

Remove mirror default of True

---

CHANGES/612.bugfix
pulp_deb/app/tasks/synchronizing.py

Fix sync not including packages only found in component `all`

---

CHANGES/682.feature
pulp_deb/app/tasks/publishing.py

This PR breaks `_ReleaseHelper.finish()` up into three parts, `save_unsigned_metadata`, `sign_metadata`, and `save_signed_metdata`, and then calls `sign_metadata` concurrently for all releases at once.
There are potentially many other ways to accomplish the same thing, but this seemed the simplest to me. We don't have to worry about thread management or locking. The database driver doesn't have to be async compatible. An the overall semantics of the Task remain the same, it will still block the worker until it's done, it just happens much faster in environments with slow signing.
Even in `asyncio` there are other ways this could be accomplished. We could for example use `asyncio.Tasks` and `asyncio.wait`. The benefit of `asyncio.gather` is simplicity, and it also offers by default …

#682: Sign the metadata for all releases in a repo concurrently, greatly speeding up the publish task in environments where signing is slow.

---

CHANGES/592.removal

[noissue]
This is an addition to the as of yet unreleased issue #592
This PR has resulted from this discussion: https://discourse.pulpproject.org/t/unable-to-upload-packages-to-rpm-repo-if-allready-stored-in-pulp/841
Note that the new behaviour is currently only for generic and the various package content, but not for metadata/upstream metadata content. This could be pretty confusing for people. Maybe we should have the new behavior for all content API endpoints? (The reason we did things the way we did, is because we set out to simplify the package upload workflow).

Add removal warning about changed upload API behaviour

---

CHANGES/646.feature
pulp_deb/app/viewsets/content.py

These new filters allow you to ask the questions "What Packages are in the current version of this Release?" or "What ReleaseComponents contain this Package?" Examples:
```
/pulp/api/v3/content/deb/packages/?release=<release_uuid>,<repo_version_href>
/pulp/api/v3/content/deb/packages/?release_component=<release_component_uuid>,<repo_version_href>
/pulp/api/v3/content/deb/releases/?package=<package_uuid>,<repo_version_href>
/pulp/api/v3/content/deb/release_components/?package=<package_uuid>,<repo_version_href>
```
It also provides a simple framework by which any similar types of filters can be added, and an explanation about why it works the way it does.

#646: Add filters to select by related pulp_deb content types

---

CHANGES/780.misc
pulp_deb/app/viewsets/content.py
pulp_deb/tests/functional/api/test_sync.py
pulp_deb/tests/functional/conftest.py

And make filters return empty list if content not in RepoVersion instead of raising a ValidationError, which I believe to be more correct behavior.
closes #780

Add tests for related content filters

---

CHANGES/777.bugfix
pulp_deb/app/tasks/publishing.py

When publishing a package that doesn't have a matching architecture in the release component, a KeyError gets thrown. This fixes it so that a warning message is instead logged.
One option would have been to fail the publish with a more user friendly error. However, in our use case, repos are shared across different users/teams so if one team adds a package with an unsupported arch, no one can publish the repo (which is bad). 
In the future, I think it would be good to add some validation to the repo modify endpoint to prevent packages with unsupported architectures from being added to repos.

Fixed KeyError during publish for unmatched arch

---

CHANGES/806.bugfix
pulp_deb/app/migrations/0021_remove_release_from_structure_types.py

[noissue]
The previous version cannot work, but no one noticed, since it is not released yet, and is only designed to catch a rare edge case when unapplying the migration 0021.

Fix content creation when unapplying migration 0021

---

CHANGES/807.bugfix
pulp_deb/app/serializers/content_serializers.py

closes #807
List of chagnes:
- Added a info level log message about the structured upload.
- Ensured any extra content created is added to the created_resources list of the relevant task.
- Stopped using the blanket suppression of IntegrityError, which appears to have fixed repeated uploads to a repo not working as designed.
(cherry picked from commit d04da37906bf9ad0e80398c9efddb78f4dceca2a)

Rework structured upload backport to 2.21

---

CHANGES/796.misc
functest_requirements.txt
pulp_deb/tests/functional/api/test_crud_content_unit.py
pulp_deb/tests/functional/api/test_crud_packages.py
pulp_deb/tests/functional/api/test_crud_remotes.py
pulp_deb/tests/functional/api/test_download_content.py
pulp_deb/tests/functional/api/test_download_policies.py
pulp_deb/tests/functional/api/test_publish.py
pulp_deb/tests/functional/api/test_sync.py
pulp_deb/tests/functional/conftest.py
pulp_deb/tests/functional/constants.py
pulp_deb/tests/functional/utils.py
requirements.txt

Remove pulp smash

---

pulp_deb/tests/functional/api/test_download_policies.py
pulp_deb/tests/functional/api/test_pulpexport_pulpimport.py

Due to some recent pulpcore changes we needed to adapt some tests in order to fix the CI pipelines.
See: https://github.com/pulp/pulpcore/pull/4477 https://github.com/pulp/pulpcore/pull/4494

Fix ci tests

---

CHANGES/903.bugfix
pulp_deb/app/tasks/synchronizing.py
pulp_deb/tests/functional/api/test_sync.py
pulp_deb/tests/functional/conftest.py

This PR achieves the following:
- Do not disable optimize if we are switching from mirror to not mirror between two syncs. We can optmize in this case.
- Log additional reasons why we did not optimize in certain cases.
- Improve the readability of optimize conditions.

Improve optimize sync conditions

---

pulp_deb/tests/functional/api/test_pulpimport.py

Backport 2.21: Make import tests agnostic to .tar vs .tar.gz

---

CHANGES/795.feature
docs/feature_overview.rst
pulp_deb/app/settings.py
pulp_deb/app/tasks/publishing.py

This PR is to continue the work of adamsanaglo for AptByHash. It includes code changes for mitigating the Hash Sum Mismatch error by generating additional metadata files named by checksum for AptByHash, as well as changes advised by quba in the adamsanaglo's original PR.
Closes #795

Continuing #833 RE: Generating Checksum Named Files for AptByHash

---

CHANGES/926.feature
pulp_deb/app/serializers/content_serializers.py
pulp_deb/app/viewsets/content.py

closes #926
I'm also changing the `view_name` of the fields in `SourcePackageReleaseComponentSerializer`, which _might_ be fixing a bug? But if it is it's fixing an unreleased bug, so whatever. But I could not get creating a new `SourcePackageReleaseComponent` object over the API to work properly without this, instead it would would return a `Invalid hyperlink - No URL match.` error for each field.

Add extra filters linking SourcePackages to Releases and ReleaseComponents

---

docs/plugin_maintenance.rst

Update the plugin maintenance docs

---

CHANGES/976.bugfix
pulp_deb/app/models/publication.py

This prevents the content app from serving unpublished content when a repo is set on a distribution:
https://github.com/pulp/pulpcore/commit/27a0dc7424769b2d5d7e98ebc4cf9cdba6cdc149
Also, this setting will be used to protect repo versions once the repo version protection work is merged:
https://github.com/pulp/pulpcore/pull/4750
fixes #976

Set SERVE_FROM_PUBLICATION on AptDistribution

---

CHANGES/984.bugfix
pulp_deb/app/tasks/publishing.py

Fix APT_BY_HASH setting

---

CHANGES/1019.bugfix
pulp_deb/app/tasks/synchronizing.py
pulp_deb/tests/functional/api/test_publish.py

closes #1019
We no longer want to see warnings like the following in the log:
pulpcore-worker: /usr/lib/python3.9/site-packages/debian/deb822.py:716: UserWarning: Parsing of Deb822 data with python3-apt’s apt_pkg was requested but this package is not importable. Is python3-apt installed?

Suppress the warnings about python3-apt not being installed

---

CHANGES/1019.bugfix
pulp_deb/app/tasks/synchronizing.py
pulp_deb/tests/functional/api/test_publish.py

(cherry picked from commit 98d826674f203317e615c3568ff67f2ceb82c6c4)

[PR #1020/98d82667 backport][3.0] Suppress the warnings about python3-apt not being installed

---

CHANGES/1053.bugfix
pulp_deb/app/tasks/publishing.py
pulp_deb/tests/functional/api/test_source_package.py
pulp_deb/tests/functional/conftest.py

Handle a source package publish IntegrityError when a source package belongs to multiple dists.
fixes #1053

Fix source package publish error

---

CHANGES/1053.bugfix
pulp_deb/app/tasks/publishing.py

Because of the performance tests which split the `conftest.py` and the fact that the source package publish fix uses fixtures introduced in the "add retrieve functionality" there were a lot of merge conflicts which I had to fix manually.
If we don't want to backport the "add retrieve functionality" feature we can just close this PR

Backport 3.1: add retrieve functionality / fix source package publish

---

CHANGES/1077.feature
CHANGES/1077.removal
pulp_deb/app/serializers/content_serializers.py

Remove the checking of existing source debs and instead return the existing source package. Fixes #1077

Remove the checking of existing source debs

---

CHANGES/1038.feature
CHANGES/1038.removal
docs/_scripts/structured_repo.sh
pulp_deb/app/serializers/content_serializers.py
pulp_deb/app/viewsets/content.py
pulp_deb/tests/functional/api/test_crud_packages.py
pulp_deb/tests/functional/conftest.py

This PR adds the following: 
1. Allows for a single api call to create release, components, and architectures. 
2. Adds retrieve functionality to the release creation endpoint. If a release already exists, then the existing release will be retrieved. 
3. The release creation endpoint did not originally return a task, which is a bug since it can add content to a repository. This PR updates the endpoint to return a task.
closes #1038

Create architectures and components when creating a release

---

CHANGES.md

The warning need to be marked differently in Markdown.
[noissue]

Fix changelog after conversion from RST

---

docs/workflows/sync.rst

(Might be a good idea to run a spell check linter 😄 )

docs: fix repository typo

---

CHANGES/1115.misc
pulp_deb/app/tasks/publishing.py

Improve queries in publish task to utilize select_related

---

pulp_deb/app/tasks/publishing.py

Fix a source publishing bug that was introduced in https://github.com/pulp/pulp_deb/commit/b29542e8ddb547fec1c8607148fda51e65d9b99e where the code was looping through all release components instead of just the release components for the distribution when attempting to publish source files for a specific distribution component. This raised a key error that was found in @acheng-01's PR #1061 which added a test for source publishing.

Fix source publish bug

---

.github/workflows/scripts/install.sh
CHANGES/1059.feature
pulp_deb/app/tasks/publishing.py
pulp_deb/tests/functional/api/test_download_content.py
template_config.yml

Refactored the previous AptByHash code to extend publishing at by-hash paths for source files.
Closes #1059

Allow source files to publish at by-hash paths

---

CHANGES/1147.feature
pulp_deb/app/serializers/content_serializers.py
pulp_deb/app/tasks/publishing.py

Add package and source package batching for publish

---

CHANGES/+add-dsc-sha256.feature
pulp_deb/app/models/content/content.py
pulp_deb/app/serializers/content_serializers.py
pulp_deb/app/viewsets/content.py

We'd like to be able to have a sha256 column for Source Packages like we do for packages. This would save us an extra call to the artifact endpoint.
[noissue]

Expose the sha256 for source package dsc files

---

CHANGES/1190.bugfix
pulp_deb/app/viewsets/repository.py
pulp_deb/tests/functional/api/test_publish.py

Fixed PRC not getting removed when modifying repositories

---

pulp_deb/app/management/commands/check_dangling_content.py

Add utility script to detect dangling PRCs in structured content

---

pulp_deb/tests/functional/api/test_crud_packages.py
pulp_deb/tests/functional/api/test_crud_remotes.py
pulp_deb/tests/functional/api/test_duplicate_packages.py
pulp_deb/tests/functional/api/test_rbac.py
pulp_deb/tests/functional/api/test_source_package.py
pulp_deb/tests/functional/api/test_sync.py
pyproject.toml

Adjusting a number of tests to the stricter pydantic requirements.

Bump pulpcore upper bounds to 3.85

---

CHANGES/1309.bugfix
pulp_deb/app/models/repository.py
pulp_deb/tests/unit/test_models.py

This happens if repository-versions exist with different releases that have the same value for 'distribution'. If we copy packages between these repository-versions, then release would be copied as well due to structured-content. Multiple releases in a repository-version is only allowed, if they differ in 'distribution', resulting in validate_duplicate_content() reporting an error.
Also removed remove_duplicate_content(), because it never did anything being called after validate_duplicate_content()
closes #1309

Fix duplicate release-content during copy

---

.github/workflows/scripts/install.sh
template_config.yml

Set storage settings in template_config.yml based on pulpcore requirement (>=3.49.0,<3.85).
Storage formats: Azure (legacy), S3 (new STORAGES)
This addresses the recent change where plugin-template stopped automatically setting test scenario storage settings and now requires plugins to define them in their template_config.yml.

Update Azure and S3 storage settings for 3.5

---

CHANGES/1332.misc
pulp_deb/app/tasks/synchronizing.py
pulp_deb/tests/unit/test_gpg_agent_cleanup.py

Whenever a private key is imported via `python-gnupg`, this leads to a `gpg-agent` daemon process for the specified gpg home directory. This process will usually run until its socket file in the gpg home directory is removed, which we do once the temporary directory is cleaned up.
Unfortunately, a race condition can happen between the files the `gpg-agent` manipulates inside the `gpg-home` directory and the temporary directory cleanup, which can e.g. manifest in an error like: `[Errno 39] Directory not empty: 'gpg-home'`
There is a way to stop the `gpg-agent` belonging to a specific gpg home directory by calling `gpgconf`. By doing this right after we import the private key, we ensure that no `gpg-agent` process is running for our gpg home directory. All other methods we currently use …

Terminate gpg-agent process after priv. key import
