docs/conf.py
=> Updates extlinks and its usages to use redmine

AUTHORS
I added myself to the AUTHORS file.
=> add aschieb to AUTHORS

pulp-dev.py, test_requirements.txt
Also, configure pulp-dev.py to install the packages.
=> Add test requirements.

plugins/test/unit/__init__.py
https://pulp.plan.io/issues/413
re #413
=>  Block attempts to load server.conf when running tests

plugins/pulp_deb/plugins/importers/sync.py, plugins/test/unit/plugins/importers/test_sync.py, pulp-deb.spec
=> feed_url looks closer to sources.list

plugins/pulp_deb/plugins/distributors/distributor.py, plugins/test/unit/plugins/distributors/test_distributor.py
Update documentation accordingly
=> Bugfix: Cleanup the distributor on deleting a repository

.pep8speaks.yml
Closes #2765
Change-Id: Ia58fd60c7503d8e9094a5a1d67cb03071d261932
=> Added .pep8speaks.yml

README.md, common/pulp_deb/common/constants.py, plugins/pulp_deb/plugins/importers/sync.py, plugins/test/unit/plugins/importers/test_sync.py, pulp-dev.py
This is a feature i wanted to implement for a long time...
@mibanescu Tests will follow. ;)
=> Implement remove_missing

plugins/pulp_deb/plugins/distributors/configuration.py, plugins/test/unit/plugins/distributors/test_configuration.py, plugins/test/unit/plugins/distributors/test_distributor.py
=> 2.16.4 Cherrypicks

.travis.yml, extensions_admin/pulp_deb/extensions/admin/repo_create_update.py, extensions_admin/pulp_deb/extensions/admin/repo_options.py, plugins/pulp_deb/plugins/distributors/configuration.py, plugins/pulp_deb/plugins/importers/importer.py, plugins/test/unit/plugins/distributors/test_distributor.py, pulp-dev.py
Fixes #3937
https://pulp.plan.io/issues/3937
=> Make flake8 happy

pulp-dev.py
This is required to satisfy flake8 on Travis CI.
See https://pulp.plan.io/issues/4389
=> Fix indentation in pulp-dev.py

.travis/script.sh, docs/installation.rst
Required PR: pulp/pulp#3882
closes #4187
https://pulp.plan.io/issues/4187
=> Use hyphens for Pulp3' system units name.

README.md
I have been asked regarding InRelease file support in pulp_deb by several different people by now.
Well, it turns out, this is merely a matter of configuration!
To let people know of this happy news, I have added some relevant documentation to the `README.md` file.
=> Add documentation on InRelease files

.travis/script.sh, docs/installation.rst, pulp_deb/tests/functional/api/test_download_content.py
re: #4450
https://pulp.plan.io/issues/4450
=> Replace use of pulp-manager with django-admin

pulp_deb/app/models.py, pulp_deb/app/viewsets.py, pulp_deb/tests/functional/constants.py
=> Rename model types to be unique

.travis/script.sh, docs/installation.rst, docs/workflows/index.rst, docs/workflows/publish.rst, docs/workflows/sync.rst, docs/workflows/upload.rst
Change Pulp 3 Default Ports
https://pulp.plan.io/issues/4556
docs updates too:
https://pulp.plan.io/issues/4594
Content: 8080 -> 24816
API: 8000 -> 24817
[noissue]
Required PR: https://github.com/pulp/pulpcore/pull/75
=> Change Pulp 3 Default Ports

plugins/pulp_deb/plugins/migrations/0004_add_distribution.py
fixes #4884
https://pulp.plan.io/issues/4884
=> Fix the logging in migration 0004

plugins/test/unit/plugins/distributors/test_distributor.py
Some assertions were silently not being called.
Added extra assertions to ensure this cannot happen in the future.
=> Repair test_publish_repo

plugins/pulp_deb/plugins/migrations/0004_add_distribution.py
This fix prevents KeyErrors during migration 0004.
These can happen when there are importers with empty "config" dict.
fixes #4924
https://pulp.plan.io/issues/4924
=> Fix migration 0004 for importers with empty config

.travis.yml
Solution: update using plugin template
[noissue]
=> Problem: travis config out of date

CHANGES/5405.bugfix, pulp_deb/app/models.py, pulp_deb/tests/functional/api/test_download_policies.py
* Add download_policies test
fixes #5405
https://pulp.plan.io/issues/5405
=> Fix publishing of deferred downloads

pulp_deb/__init__.py, setup.py
=> Bump version

CHANGES/5477.misc, pulp_deb/app/tasks/synchronizing.py
closes #5477
https://pulp.plan.io/issues/5477
Required PR: https://github.com/pulp/pulpcore/pull/293
Required PR: https://github.com/pulp/pulpcore-plugin/pull/127
Required PR: https://github.com/pulp/pulp_file/pull/277
=> Replace ProgressBar with ProgressReport

.travis.yml, .travis/before_install.sh, .travis/install.sh
=> Update travis ci scripts

pulp_deb/app/viewsets.py
=> Improve content filters

docs/installation.rst
=> Fix docs due to renaming of pulpcore-content-app to pulpcore-content

CHANGES/5548.removal, pulp_deb/tests/functional/api/test_download_policies.py, pulp_deb/tests/functional/api/test_publish.py, pulp_deb/tests/functional/api/test_sync.py, pulp_deb/tests/functional/api/test_upload.py
_versions_href to pulp_versions_href
_latest_version_href to pulp_latest_version_href
ref #5548
https://pulp.plan.io/issues/5548
Required PR: https://github.com/pulp/pulpcore/pull/329
Required PR: https://github.com/PulpQE/pulp-smash/pull/1221
=> Renaming RepositoryVersion fields

CHANGES/5543.bugfix, pulp_deb/app/serializers/content_serializers.py
related to:
issue: https://pulp.plan.io/issues/5543
PR: https://github.com/pulp/pulpcore-plugin/pull/143
[noissue]
=> Fix fields filter

.travis.yml, .travis/before_install.sh, .travis/install.sh, .travis/script.sh, .travis/validate_commit_message.py, CHANGES/5580.misc, pulp_deb/app/settings.py, setup.py
=> Update travis config; Depend on pulpcore

pulp_deb/app/viewsets.py, pulp_deb/tests/functional/api/test_download_policies.py, pulp_deb/tests/functional/api/test_publish.py, pulp_deb/tests/functional/api/test_sync.py
* Add modify endpoint to repositories
* Do not rely on version increment in tests
[noissue]
=> Update to breaking changes

CHANGES.rst, CHANGES/4544.feature, CHANGES/5377.feature, CHANGES/5457.removal, CHANGES/5543.bugfix, CHANGES/5548.removal, CHANGES/5550.removal, CHANGES/5580.misc, CHANGES/5698.removal, pulp_deb/__init__.py, setup.py
=> Bump version and generate changelog

pulp_deb/app/models.py, pulp_deb/tests/functional/api/test_download_policies.py, pulp_deb/tests/functional/api/test_sync.py
Also fix tests for empty repository_version.
[noissue]
=> Add CONTENT_TYPES to repository

.travis/before_install.sh, .travis/install.sh, .travis/publish_client_pypi.sh, .travis/publish_plugin_pypi.sh, .travis/script.sh, .travis/validate_commit_message.py, pulp_deb/app/models/content.py, template_config.yml
=> Update travis config

COPYRIGHT
=> Adds COPYRIGHT file like other pulp org repos

pulp_deb/app/tasks/synchronizing.py
Do not attempt to 'download' generated temporary files. Create artifacts
directly instead.
[noissue]
=> Fix synching

.travis.yml, .travis/before_install.sh, .travis/before_script.sh, .travis/install.sh, .travis/script.sh, template_config.yml
=> Use fixtures_container; Update travis config

CHANGES/6393.misc, functest_requirements.txt, pulp_deb/tests/functional/utils.py
https://pulp.plan.io/issues/6339
closes #6339
=> Get bindings host from pulp-smash

pulp_deb/app/models/signing_service.py
[noissue]
With the fix for https://pulp.plan.io/issues/6342 we can now inherit
functionally exactly these methods from the parent class.
Depends on https://github.com/pulp/pulpcore/pull/584 (but that has already been merged to the same pulpcore version we are already on)
=> Use the signing service methods from the parent class

.travis/install.sh
[noissue]
See also https://pulp.plan.io/issues/6767
=> Use fixtures container from docker.io

.travis/release.py, .travis/script.sh, .travis/validate_commit_message.py, template_config.yml
[noissue]
Added 'redmine_project: pulp_deb' to template config and ran the
following using the latest plugin_template repo:
./plugin-template --travis
=> Add redmine_project to template config

.travis/smash-config.json
See https://github.com/pulp/pulp-fixtures/pull/160
[noissue]
=> Updating fixture path

CHANGES/6907.feature, pulp_deb/app/tasks/publishing.py
Add new fields to release file
fixes #6907
https://pulp.plan.io/issues/6907
=> Add Release file fields

CHANGES/6908.bugfix, pulp_deb/app/serializers/remote_serializers.py
Fix nullable DB fields which could not be set to null via the API
fixes #6908
https://pulp.plan.io/issues/6908
=> Fix nullable DB fields to set to null via the API

pulp_deb/app/viewsets/publication.py, pulp_deb/app/viewsets/repository.py
Required PR: https://github.com/pulp/pulpcore/pull/785
[noissue]
=> OpenAPI v3 with drf-spectacular

CHANGES/6051.misc, CHANGES/7295.bugfix, pulp_deb/app/models/content.py, pulp_deb/app/tasks/publishing.py, pulp_deb/app/tasks/synchronizing.py, pulp_deb/tests/functional/api/test_publish_complex_dists.py, pulp_deb/tests/functional/constants.py
fixes #6051
https://pulp.plan.io/issues/6051
=> Add test for known cases where distribution is not codename or suite

CHANGES/7153.bugfix, pulp_deb/app/models/content.py
fixes #7153
https://pulp.plan.io/issues/7153
=> Fix relative path of packages

.travis/release.py, CHANGES/7344.misc, pulp_deb/app/models/content.py, pulp_deb/app/serializers/remote_serializers.py, pulp_deb/app/tasks/publishing.py, pulp_deb/tests/functional/api/test_publish_empty_repository.py, pulp_deb/tests/functional/setup_signing_service.py
fixes #7344
https://pulp.plan.io/issues/7344
=> Add tests for publishing empty repository

.bumpversion.cfg, CHANGES/.TEMPLATE.rst, MANIFEST.in, flake8.cfg
[noissue]
Generated by running the following in the plugin template repo:
./plugin-template --bootstrap pulp_deb
Manually edited and selectively added!
=> Add select plugin template bootstrap changes

.travis/validate_commit_message.py, pyproject.toml
I am opening this as a draft pull request, because I need some help with evaluating the changes to `pyproject.toml` (which came from the plugin template).
=> Deprecation issues

.bumpversion.cfg
[noissue]
I forgot to remove these in my previous PR.
=> Remove remaining beta tags

.travis/release_requirements.txt, README.md, docs/external_references.rst, docs/index.rst, docs/plugin_maintenance.rst
[noissue]
Documents the lessons/process from https://github.com/pulp/pulp_deb/pull/206
=> Add plugin maintenance doc

.travis.yml, .travis/Containerfile.j2, .travis/before_install.sh, .travis/docs-builder.py, .travis/publish_docs.sh, .travis/release.py, .travis/start_container.yaml, .travis/update_redmine.sh, .travis/validate_commit_message.py, template_config.yml
Latest changes from the 2020.09.23 tag in the plugin template.
=> Update plugin template

.bumpversion.cfg, CHANGES.rst, pulp_deb/__init__.py, requirements.txt, setup.py
This is a pure compatibility release.
=> Release 2.7.0

CHANGES/7502.feature, docs/external_references.rst, docs/feature_overview.rst, docs/workflows/sync.rst, pulp_deb/app/serializers/remote_serializers.py, pulp_deb/app/tasks/publishing.py, pulp_deb/app/tasks/synchronizing.py, pulp_deb/tests/functional/api/test_publish_flat_repo_format.py, pulp_deb/tests/functional/constants.py
fixes #7502
https://pulp.plan.io/issues/7502
=> Support flat repo format

.github/workflows/scripts/post_before_script.sh, MANIFEST.in, dev_requirements.txt, flake8.cfg, pyproject.toml
=> WIP: Fix the new GitHub actions CI pipeline

CHANGES/7886.feature, pulp_deb/app/serializers/content_serializers.py, pulp_deb/app/tasks/publishing.py, pulp_deb/app/tasks/synchronizing.py
fixes #7886
https://pulp.plan.io/issues/7886
=> Make codename an optional field

pulp_deb/tests/unit/test_models.py
=> Fix unit test artifact mocking

.github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/scripts/script.sh
This should hopefully fix docs publishing.
[noissue]
Generated usign:
./plugin-template --github pulp_deb
Plugin template commit:
f02e5898fdcccf502127277b4ff7c27d3620f8fa
=> Add latest plugin template changes

.ci/scripts/docs-builder.py, .ci/scripts/release.py, .ci/scripts/release_requirements.txt, .github/workflows/scripts/script.sh, template_config.yml
[noissue]
Generated using:
./plugin-template --github pulp_deb
Plugin template commit:
8f03fe956d9715e3a77e445bbc4b2ffa6592f5d3
=> Add latest pipeline changes from the plugin template

README.md, docs/_static/api.json, docs/external_references.rst, docs/plugin_maintenance.rst
This PR adds several small documentation improvements:
- A minor change to the README
- Updated plugin template usage instructions
- A updating API docs how to
- Also updates the `docs/_static/api.json` file
=> Doc improvements

pulp_deb/app/models/content.py, pulp_deb/app/models/publication.py, pulp_deb/app/models/remote.py, pulp_deb/app/models/repository.py, pulp_deb/app/models/signing_service.py, pulp_deb/app/serializers/content_serializers.py, pulp_deb/app/tasks/publishing.py, pulp_deb/app/tasks/synchronizing.py
These cosmetic issues were bothering me while working on other things. :wink:
[noissue]
* Remove unused loggers
* Replace deprecated warn() calls with warning()
* Use gettext function for all log messages
* Name all loggers "log"
=> Cleanup logging

CHANGES/8307.removal, pulp_deb/app/models/signing_service.py, pulp_deb/tests/functional/sign_deb_release.sh, requirements.txt
This is a direct consequence of https://github.com/pulp/pulpcore/pull/1012
fixes #8307
https://pulp.plan.io/issues/8307
=> Update AptReleaseSigningService validation

.ci/scripts/docs-builder.py, .ci/scripts/release_requirements.txt, docs/plugin_maintenance.rst, template_config.yml
=> Update CI files

.ci/scripts/publish_client_gem.sh, .ci/scripts/publish_client_pypi.sh, .ci/scripts/publish_plugin_pypi.sh, .github/workflows/release.yml
[noissue]
Applied using:
./plugin-template --github pulp_deb
Applied from the following plugin_template commit:
167a6027f628fb8f900d7850b18ec9ba9d749bad
=> Apply latest plugin template changes

pulp_deb/app/tasks/publishing.py
=> Replace workingdir with Python stdlib

CHANGES/8520.feature, pulp_deb/app/models/repository.py, pulp_deb/app/viewsets/repository.py
fixes #8520
https://pulp.plan.io/issues/8520
=> Allow remotes to be associated with repositories

CHANGES/8410.bugfix, pulp_deb/app/tasks/synchronizing.py
Fixes #8410
https://pulp.plan.io/issues/8410
https://pulp.plan.io/issues/8096
=> Fix translation file synchronization

.ci/ansible/settings.py.j2, .ci/scripts/publish_client_gem.sh, .ci/scripts/publish_client_pypi.sh, .ci/scripts/publish_plugin_pypi.sh, .ci/scripts/release.py, .ci/scripts/validate_commit_message.py, .github/workflows/release.yml, .github/workflows/scripts/before_install.sh, .github/workflows/scripts/check_commit.sh, template_config.yml
=> Fix client gem publishing for the release CI

.ci/ansible/settings.py.j2, .ci/scripts/publish_client_gem.sh, .ci/scripts/publish_client_pypi.sh, .ci/scripts/publish_plugin_pypi.sh, .ci/scripts/release.py, .ci/scripts/validate_commit_message.py, .github/workflows/release.yml, .github/workflows/scripts/before_install.sh, .github/workflows/scripts/check_commit.sh, template_config.yml
=> Apply latest plugin template

CHANGES/6948.misc, pulp_deb/app/tasks/synchronizing.py
Closes #6948
https://pulp.plan.io/issues/6948
=> Log warning if component or architecture does not exist

CHANGES/8910.bugfix, pulp_deb/app/tasks/synchronizing.py
Closes #8910
https://pulp.plan.io/issues/8910
=> Ensure architecture filtering does not remove all architecture

CHANGES/8506.bugfix, functest_requirements.txt, pulp_deb/app/serializers/content_serializers.py, pulp_deb/app/tasks/synchronizing.py, pulp_deb/tests/functional/api/test_publish_complex_dists.py, pulp_deb/tests/unit/test_models.py
Closes #8506
https://pulp.plan.io/issues/8506
=> Add missing "Size" field in publications

CHANGES.rst, CHANGES/6948.misc, CHANGES/8506.bugfix, CHANGES/8910.bugfix, CHANGES/9036.removal
=> Building changelog for 2.14.0

docs/feature_overview.rst
=> Fix several small mistakes in the feature overview docs

docs/bindings.rst, docs/external_references.rst, docs/index.rst, docs/plugin_maintenance.rst
=> Update release process documentation

CHANGES/9186.doc, docs/bindings.rst, docs/external_references.rst, docs/installation.rst, docs/plugin_maintenance.rst
Closes #9186
https://pulp.plan.io/issues/9186
=> Rework the installation docs to stop being harmfull

docs/workflows/publish.rst
[noissue]
Signed-off-by: ushen <yshxxsjt715@gmail.com>
=> Add some details

docs/workflows/sync.rst
https://pulp.plan.io/issues/9147
[noissue]
=> Add a note about scheduling tasks

CHANGES/9333.misc, pulp_deb/app/serializers/content_serializers.py
Fixes #9333
https://pulp.plan.io/issues/9333
=> Ignore package fields with corrupt values

docs/external_references.rst, docs/plugin_maintenance.rst
=> Update community discussion URLs

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/scripts/install.sh, .github/workflows/scripts/post_before_script.sh, template_config.yml
=> Activate azure tests

CHANGES/8770.bugfix, pulp_deb/app/serializers/content_serializers.py
closes #8770
https://pulp.plan.io/issues/8770
=> Drop package paragraph fields without values

CHANGES/9555.feature, docs/workflows/sync.rst, pulp_deb/app/settings.py, pulp_deb/app/tasks/synchronizing.py
closes #9555
https://pulp.plan.io/issues/9555
=> Add FORCE_IGNORE_MISSING_PACKAGE_INDICES setting

requirements.txt
Ref: https://github.com/pulp/pulp-oci-images/runs/4281508066?check_suite_focus=true
https://github.com/pulp/pulp-oci-images/pull/132
=> Fix 2.14 broken builds

CHANGES.rst
[noissue]
(cherry picked from commit 33df509939a1702fbc9dbc5f2afd6fd44b241c38)
=> Cherry pick 2.16.1 changelog

README.md
=> Update the CI/CD status badge URLs

requirements.txt
=> Add upper bounds to requirements for release CI

pulp_deb/app/__init__.py
=> Add python_package_name for 3.20 compatibility

pulp_deb/tests/functional/api/test_crud_remotes.py, pulp_deb/tests/functional/conftest.py
=> Rewrite remote repository crud test to use pytest framework

CHANGES/571.bugfix, pulp_deb/app/tasks/synchronizing.py
=> Sanitize package path before downloading

CHANGES/575.bugfix, pulp_deb/app/serializers/content_serializers.py
=> Fixing content serializer bugs

.github/workflows/scripts/post_docs_test.sh, CHANGES/586.docs, docs/_scripts/setup.sh, docs/_scripts/structured_repo.sh, docs/workflows.rst, docs/workflows/structured_repo.rst
The script in the docs will be tested by the CI:
https://github.com/pulp/pulp_deb/blob/0429dddf355f7917b047b2696fc15148c641cc8e/.github/workflows/scripts/script.sh#L20
https://github.com/pulp/pulp_deb/blob/0429dddf355f7917b047b2696fc15148c641cc8e/.github/workflows/scripts/script.sh#L41-L43
=> Add structured repo docs

pulp_deb/tests/functional/api/test_download_content.py
=> Convert download content test to pytest

CHANGES/603.bugfix, pulp_deb/app/models/repository.py, pulp_deb/app/tasks/exceptions.py
=> Do not allow duplicate distributions in a single repo version

CHANGES/624.doc, docs/external_references.rst, docs/feature_overview.rst
=> Add feature overview documentation for Import/Export

pulp_deb/app/tasks/synchronizing.py
=> Do not use optimize sync when mirror=True

pulp_deb/tests/functional/api/test_crud_remotes.py, pulp_deb/tests/functional/api/test_download_content.py, pulp_deb/tests/functional/api/test_download_policies.py, pulp_deb/tests/functional/api/test_publish.py, pulp_deb/tests/functional/api/test_sync_optimize.py, pulp_deb/tests/functional/conftest.py
=> Convert download policies test to pytest

docs/index.rst, docs/quickstart.rst
Started messing with Pulp and had a pretty simple issue (#531).
Thought it would be a good idea to create a quickstart so others do not fall for the same issue.
Signed-off-by: Tim Beermann <beermann@osism.tech>
=> added a quickstart documentation

README.md
=> Add links to pulp-cli-deb to the README

pulp_deb/tests/functional/api/test_download_policies.py
=> Fix download_policies test for the CI

CHANGES/674.bugfix, pulp_deb/app/tasks/publishing.py
=> Fix packages missing from Packages index

doc_requirements.txt, docs/Makefile
=> Add doc build changes from plugin_template

pulp_deb/app/tasks/copy.py
[noissue]
This was broken by commit f5bb7c8b6e1d50ec2a6d40029152e6d9ca3704ea
I am adding this fix now, but we also need a regression test.
=> Fix structured copy

CHANGES/765.doc, doc_requirements.txt, docs/conf.py
=> Fix infinite loading in the docs search bar

CHANGES/765.doc, doc_requirements.txt, docs/conf.py
closes #765
(cherry picked from commit 86635947f3e65473192ada28a40a941f69d46f60)
=> Backport 2.20: Fix infinite loading in the docs search bar

CHANGES/765.doc, doc_requirements.txt, docs/conf.py
closes #765
(cherry picked from commit 86635947f3e65473192ada28a40a941f69d46f60)
=> Backport 2.19: Fix infinite loading in the docs search bar

CHANGES/765.doc, doc_requirements.txt, docs/conf.py
closes #765
(cherry picked from commit 86635947f3e65473192ada28a40a941f69d46f60)
=> Backport 2.18: Fix infinite loading in the docs search bar

.github/workflows/scripts/install.sh, .github/workflows/scripts/script.sh, template_config.yml
=> Test pulp-cli-deb

pulp_deb/tests/unit/test_models.py
=> Fix failing unit test

pulp_deb/tests/unit/test_models.py
[noissue]
(cherry picked from commit 3e61da36805a2f6339d2c8b840272a163544cb3f)
=> Backport 2.21: Fix failing unit test

CHANGES/790.misc, pulp_deb/tests/functional/api/test_download_content.py, pulp_deb/tests/functional/api/test_download_policies.py, pulp_deb/tests/functional/api/test_publish.py, pulp_deb/tests/functional/api/test_sync.py, pulp_deb/tests/functional/conftest.py
=> Updated the scoping of the pytest fixtures.

CHANGES/797.bugfix, pulp_deb/app/tasks/synchronizing.py
=> Fix async issues

pulp_deb/tests/functional/api/test_sync.py
=> Check `done` instead of `total` in sync test

pulp_deb/tests/functional/api/test_sync_optimize.py
=> Backport 2.20: Check `done` instead of `total` in sync test

CHANGES/779.doc, docs/bindings.rst, docs/external_references.rst, docs/installation.rst
=> Replace the Pulp Ansible installer with the OCI images in the docs

CHANGES/598.doc, docs/external_references.rst, docs/installation.rst
=> Add documentation for installing pulp-cli-deb

pulp_deb/tests/functional/api/test_download_policies.py, pulp_deb/tests/functional/api/test_sync.py, pulp_deb/tests/functional/conftest.py
=> Changed `deb_get_content_summary` to make it more consistent

CHANGES/879.misc, pulp_deb/app/urls.py
=> Fix API root for the deb/copy/ endpoint for s3

CHANGES/758.misc, pulp_deb/tests/functional/api/test_copy.py, pulp_deb/tests/functional/conftest.py, pulp_deb/tests/functional/constants.py
=> Add tests for advanced copy task

template_config.yml
=> Add 3.0 to ci_update_branches

CHANGES/909.feature, pulp_deb/app/viewsets/content.py
=> Add additional package name filters

CHANGES/872.feature, pulp_deb/app/modelresource.py, pulp_deb/tests/functional/api/test_pulpexport_pulpimport.py, pulp_deb/tests/functional/api/test_sync.py
=> Fixed creating of repositories when importing content

CHANGES/872.feature, pulp_deb/app/modelresource.py, pulp_deb/tests/functional/api/test_pulpexport_pulpimport.py, pulp_deb/tests/functional/api/test_sync.py
(cherry picked from commit 5b17ad244566a4b7e5cd859311f8952ac5ba67ca)
=> Backport 3.0: Fix import/export not creating repositories and use the correct data

CHANGES/928.feature, requirements.txt
=> Raises pulpcore requirement to 3.40.1+

pulp_deb/tests/functional/api/test_copy.py, pulp_deb/tests/functional/api/test_download_policies.py, pulp_deb/tests/functional/api/test_publish.py, pulp_deb/tests/functional/api/test_pulpexport_pulpimport.py, pulp_deb/tests/functional/api/test_sync.py, pulp_deb/tests/functional/conftest.py, pulp_deb/tests/functional/utils.py
=> Simplify content fetching test fixtures

template_config.yml
=> Maintain the 3.1 branch

template_config.yml
[noissue]
Do we want to continue updating these?
=> Stop supporting the 2.* branches

CHANGES/919.misc, pulp_deb/tests/functional/api/test_pulp_to_pulp.py, pulp_deb/tests/functional/conftest.py, pulp_deb/tests/functional/constants.py
=> Add pulp to pulp verification tests

.github/workflows/nightly.yml, CHANGES/970.misc, pulp_deb/tests/conftest.py, pulp_deb/tests/functional/conftest.py, pulp_deb/tests/functional/constants.py, pulp_deb/tests/performance/test_publish.py, pulp_deb/tests/performance/test_pulp_to_pulp.py, pulp_deb/tests/performance/test_sync.py, template_config.yml
=> Add performance tests for pulp deb

requirements.txt
This should fix our nightly CI
[noissue]
=> Raise pulpcore requirement to 3.45.1

template_config.yml
=> Add 3.2 to the supported_release_branches

pulp_deb/tests/functional/api/test_source_package.py
=> Add test for uploading the same source package twice.

docs/feature_overview.rst
=> Update apt-by-hash docs

CHANGES/1100.feature, pulp_deb/tests/functional/api/test_download_policies.py, pulp_deb/tests/functional/api/test_pulpexport_pulpimport.py, pulp_deb/tests/functional/api/test_source_package.py, pulp_deb/tests/functional/api/test_sync.py, pulp_deb/tests/functional/conftest.py, requirements.txt
=> Raise pulpcore requirement to 3.55+

template_config.yml
=> Maintain 3.3 branch

CHANGES/1122.bugfix, pulp_deb/app/tasks/synchronizing.py
=> Fixed throwing wrong error when using custom signing service

.bumpversion.cfg
=> Remove legacy config for old docs causing issue with bumpversion script

CHANGES/1167.feature, pulp_deb/app/serializers/content_serializers.py
=> Expose the plain component to API querries

CHANGES/1250.feature, pulp_deb/app/serializers/publication_serializers.py, pulp_deb/app/tasks/publishing.py, pulp_deb/app/viewsets/publication.py, pulp_deb/tests/conftest.py, pulp_deb/tests/functional/api/test_checkpoint.py, pyproject.toml
Added the checkpoint field to AptPublicationSerializer and AptDistributionSerializer. 
Enabled creating checkpoint publications.
closes #1250
=> Add checkpoint support

CHANGES/1225.bugfix, pulp_deb/app/serializers/content_serializers.py
=> Drop custom fields with empty values

CHANGES/1258.feature, pulp_deb/app/tasks/synchronizing.py, pulp_deb/tests/functional/api/test_publish.py, pulp_deb/tests/functional/api/test_pulp_to_pulp.py, pulp_deb/tests/functional/constants.py, pulp_deb/tests/unit/test_release_file_helpers.py
=> Add better flat repo handling for structure publish

pulp_deb/app/tasks/synchronizing.py
=> Fix optimize sync for flat repos

CHANGES/1279.bugfix, pulp_deb/app/tasks/synchronizing.py
=> Fixed a flat repo edge case with zero-byte artifacts

.github/workflows/docs.yml, doc_requirements.txt
There was a intermediate state where we needed this branch, but we don't anymore.
=> Update docs workflow version
